### PR TITLE
Change favicon replacement method for working better

### PR DESCRIPTION
**Pull request by gta126**
Hi,

I have tested your chrome extension and it is very useful for me but your original method for replace favicon has not been working on https://www.mediquality.net website.

I send you another method for replace favicon which work better for me.

Best regards,
gta126

### CODE REVIEW

**Comment by ao5357** [comment]
Thank you very much for doing this! I had noticed that some favicons weren't being updated properly, but the problem was inconsistent and infrequent enough not to worry much about it.

As commented in the diff, there's a licensing question.

I've also committed to ensuring this extension is as lightweight/performant as possible. Maybe only certain aspects of the third-party script would be necessary for ensuring good favicon-ing?

Thank you once more. I'll get on this.

**Comment by ao5357** [comment]
I have pushed some updated JavaScript in e26758ced51892c32fcc711631b53373feafd0bd

This does two things:
  1. It removes previous favicons in the head before inserting a new one
  2. If a favicon is not provided by Chrome on the tab event, the extension will try to find one before using the default

If you don't mind, please test this update. If it works out over the next few days, I'll roll the update to the Chrome store.

**Comment by gta126** [comment]
Hi.

Okay. I test your code today.

gta126

**Comment by ao5357** [comment]
I have updated the extension in the chrome web store to 1.1.0, based on my commit from Jan 26.

If there are any improvements from your PR on Feb 6, please roll them as a PR against HEAD and we'll re-test and re-release with those changes included.

Going to close this PR.

Thank you for contributing code and helping to test on this project, Christophe.

**Pull request closed without merging**
