### PR TITLE
Fix targeting

### PR DESCRIPTION
**Pull request by davmillar**
- Initially fixed some deprecated event API issues with the options UI.
- Then refactored/reorganized to make the extension use a service worker and manifest v3.

### CODE REVIEW

**Comment by ao5357** [comment]
Holy goodness, @davmillar , you rock! I will review this ASAP and try to get it merged and deployed this weekend.

(btw, I had some UI improvements to fix the long-standing drag-and-drop issues on deck, but got mired in some manifest v3 conversion issues. If there's any of my un-committed work that applies I'll also get that in place. The I'm tempted to believe this extension will be 100% perfect and bug-free)

**Comment by davmillar** [comment]
> Holy goodness, @davmillar , you rock! I will review this ASAP and try to get it merged and deployed this weekend.
> 
> (btw, I had some UI improvements to fix the long-standing drag-and-drop issues on deck, but got mired in some manifest v3 conversion issues. If there's any of my un-committed work that applies I'll also get that in place. The I'm tempted to believe this extension will be 100% perfect and bug-free)

Oh no, I hope I didn't trample any of your work. I wasn't sure if this was still in active development or not but wanted to fix some pesky things since I'd just recommended the extension to my teammates. Let me know if you have a branch you want me to compare and resolve merge conflicts with, I'm happy to do that.

Most of the changes were just moving responsibilities between the content script and the background script/service worker because the SW can't touch the document directly. Along the way, I noted that some of the back and forth could be simplified to reduce the number of events thrown back and forth. I left in some of the relevant documentation but may have missed things, so feel free to ping me if those need revision as well.

Thanks again for creating this extension to begin with -- it's a big help and was a great opportunity to get back into extension development. :)

**Review by ao5357 — APPROVED** [review]
Approved as-is. Will merge immediately and manually merge in my other tweaks. That should be done this morning, though getting it out to the Google store might be another couple days. Thanks again!

**Comment by davmillar** [comment]
Heya, just wondering if the store version will be updated. I tried opening the page for it and it shows a 404 -- did its ID change or something?

**Comment by ao5357** [comment]
@davmillar According to the chrome web store developer dashboard, version 1.4.0 has been available since February 23, 2023 : https://chrome.google.com/webstore/detail/development-favicon/mopggoekgknbopeodgiodphdofgeojkb

The original development favicon did have a different id back in the day, but this newer id has been in place for about 3 years now. If you installed before then, there's a chance you have the old unmaintained version I made the mistake of putting on the store under my old work account before leaving that company.

**Pull request merged**
